import { useAuth } from "@/_core/hooks/useAuth";
import PlatformShell from "@/components/PlatformShell";
import { CourseMaterialManager } from "@/components/CourseMaterialManager";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BookOpenCheck, CalendarClock, CircleAlert, FileStack, Loader2, Plus, Route, Sparkles, UserRoundCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type Lifecycle = "draft" | "published" | "archived";
type Review = "current" | "due" | "overdue";
type LedgerFields = { contentOwner: string; businessOwner: string; reviewStatus: Review; reviewDueAt: string; version: string; changeNote: string };
type PathDraft = LedgerFields & { id?: number; title: string; description: string; level: "beginner" | "intermediate" | "advanced"; category: string; duration: string; lessonCount: number; accent: string; tags: string; prerequisitePathIds: string; lifecycleStatus: Lifecycle; isFeatured: boolean };
type CourseDraft = LedgerFields & { id?: number; pathId: number; title: string; summary: string; duration: string; orderIndex: number; resourceType: "video" | "article" | "exercise" | "template"; resourceUrl: string; tags: string; prerequisiteCourseIds: string; lifecycleStatus: Lifecycle };
const split = (value: string) => value.split(/[，,]/).map(item => item.trim()).filter(Boolean);
const splitIds = (value: string) => split(value).map(Number).filter(Number.isInteger).filter(item => item > 0);
const toInputDate = (value: Date | string | null) => value ? new Date(value).toISOString().slice(0, 10) : "";
const blankLedger = (): LedgerFields => ({ contentOwner: "待指定", businessOwner: "待指定", reviewStatus: "current", reviewDueAt: "", version: "v1.0", changeNote: "" });
const blankPath = (): PathDraft => ({ title: "", description: "", level: "beginner", category: "", duration: "", lessonCount: 0, accent: "violet", tags: "", prerequisitePathIds: "", lifecycleStatus: "draft", isFeatured: false, ...blankLedger() });
const blankCourse = (): CourseDraft => ({ pathId: 0, title: "", summary: "", duration: "", orderIndex: 10, resourceType: "article", resourceUrl: "", tags: "", prerequisiteCourseIds: "", lifecycleStatus: "draft", ...blankLedger() });
const statusTone: Record<Lifecycle, string> = { published: "bg-emerald-50 text-emerald-700", draft: "bg-amber-50 text-amber-700", archived: "bg-slate-100 text-slate-600" };
const reviewTone: Record<Review, string> = { current: "bg-sky-50 text-sky-700", due: "bg-amber-50 text-amber-700", overdue: "bg-rose-50 text-rose-700" };
const reviewText: Record<Review, string> = { current: "复审正常", due: "待复审", overdue: "复审逾期" };

export default function ContentOperations() {
  const { user, loading } = useAuth(); const [, setLocation] = useLocation(); const allowed = user?.role === "admin"; const utils = trpc.useUtils(); const { data, isLoading, isError, error, refetch } = trpc.platform.operations.get.useQuery(undefined, { enabled: allowed });
  const [path, setPath] = useState<PathDraft | null>(null); const [course, setCourse] = useState<CourseDraft | null>(null);
  const refresh = () => utils.platform.operations.get.invalidate();
  const addPath = trpc.platform.operations.addPath.useMutation({ onSuccess: () => { toast.success("学习路径已保存"); setPath(null); refresh(); }, onError: error => toast.error(error.message) });
  const updatePath = trpc.platform.operations.updatePath.useMutation({ onSuccess: () => { toast.success("学习路径台账已更新"); setPath(null); refresh(); }, onError: error => toast.error(error.message) });
  const addCourse = trpc.platform.operations.addCourse.useMutation({ onSuccess: () => { toast.success("课程已保存"); setCourse(null); refresh(); }, onError: error => toast.error(error.message) });
  const updateCourse = trpc.platform.operations.updateCourse.useMutation({ onSuccess: () => { toast.success("课程台账已更新"); setCourse(null); refresh(); }, onError: error => toast.error(error.message) });
  if (loading || (allowed && isLoading)) return <PlatformShell><div className="grid min-h-[65vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-violet-600" /></div></PlatformShell>;
  if (!allowed || !data) return <PlatformShell><main className="grid min-h-[65vh] place-items-center text-center"><div><h1 className="font-serif text-3xl font-semibold">{isError ? "运营数据加载失败" : "仅运营管理员可访问"}</h1><p className="mt-4 max-w-md text-sm leading-6 text-slate-500">{isError ? error?.message || "运营数据暂时不可用，请稍后重试。" : "课程、资源和复审台账仅对运营管理员开放。"}</p><div className="mt-6 flex justify-center gap-3">{isError && <Button variant="outline" onClick={() => void refetch()}>重试</Button>}<Button onClick={() => setLocation("/operations")}>返回运营管理</Button></div></div></main></PlatformShell>;
  const savePath = () => { if (!path) return; const payload = { ...path, reviewDueAt: path.reviewDueAt || null, changeNote: path.changeNote || null, tags: split(path.tags), prerequisitePathIds: splitIds(path.prerequisitePathIds) }; if (path.id) updatePath.mutate({ ...payload, id: path.id }); else addPath.mutate(payload); };
  const saveCourse = () => { if (!course) return; const payload = { ...course, resourceUrl: course.resourceUrl || null, reviewDueAt: course.reviewDueAt || null, changeNote: course.changeNote || null, tags: split(course.tags), prerequisiteCourseIds: splitIds(course.prerequisiteCourseIds) }; if (course.id) updateCourse.mutate({ ...payload, id: course.id }); else addCourse.mutate(payload); };
  const { learningMetrics } = data;
  return <PlatformShell><main className="mx-auto max-w-[1500px] px-5 py-8 lg:px-10"><button onClick={() => setLocation("/operations")} className="flex items-center text-sm font-medium text-slate-500 hover:text-violet-700"><ArrowLeft className="mr-2 h-4 w-4" />返回运营管理</button><div className="mt-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="section-kicker">LEARNING OPS / CONTENT LEDGER</p><h1 className="mt-2 font-serif text-4xl font-semibold">学习内容运营台账</h1><p className="mt-3 max-w-3xl text-slate-500">每条能力路径和课程都是可运营资产：明确业务与内容责任人，维护版本、资源、复审日期和生命周期，再用学习数据持续优化。</p></div><div className="flex gap-2"><Button onClick={() => setPath(blankPath())} className="rounded-full"><Plus className="mr-2 h-4 w-4" />新建学习路径</Button><Button onClick={() => setCourse({ ...blankCourse(), pathId: data.paths[0]?.id || 0 })} variant="outline" className="rounded-full"><Plus className="mr-2 h-4 w-4" />新建课程</Button></div></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Route} value={`${learningMetrics.publishedPaths}/${learningMetrics.totalPaths}`} label="路径覆盖" note="已发布 / 全部能力路径" /><Stat icon={BookOpenCheck} value={`${learningMetrics.publishedCourses}/${learningMetrics.totalCourses}`} label="课程发布" note="已发布 / 全部课程" /><Stat icon={CircleAlert} value={String(learningMetrics.resourceGaps)} label="资源缺口" note="已发布但无资源链接" /><Stat icon={CalendarClock} value={`${learningMetrics.reviewRisk} · ${learningMetrics.completionRate}%`} label="复审与完成" note="待复审/逾期项 · 平均完成率" /></section>
  <section className="mt-7 rounded-[26px] border border-violet-100 bg-violet-50/60 p-6"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white shadow-sm"><Sparkles className="h-5 w-5 text-violet-700" /></span><div><h2 className="font-serif text-xl font-semibold">运营节奏：设计、发布、复审、优化</h2><p className="mt-1 text-sm leading-6 text-slate-600">先建立草稿路径和课程台账，再由业务负责人确认任务价值、内容负责人维护资源，完成复审后发布；到期内容转为待复审或归档，不直接删除历史。</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-4"><GuideStep number="01" title="能力设计" text="定义人群、能力目标、先修关系和路径周期。" /><GuideStep number="02" title="资源交付" text="挂载可访问资源，维护课程标签、顺序和练习类型。" /><GuideStep number="03" title="双责任复核" text="指定业务与内容负责人，设置下次复审日期。" /><GuideStep number="04" title="数据优化" text="查看完成率、资源缺口和逾期项后迭代版本。" /></div></section>
  <section className="mt-7 grid gap-7 xl:grid-cols-[.95fr_1.05fr]"><div className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><Header icon={Route} title="能力路径台账" note="用路径组织成长顺序，并为每条路径保留责任、版本和复审责任。" /><div className="mt-5 space-y-3">{data.paths.map(item => <article key={item.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><h3 className="font-semibold">{item.title}</h3><Badge className={statusTone[item.lifecycleStatus]}>{item.lifecycleStatus}</Badge><Badge className={reviewTone[item.reviewStatus]}>{reviewText[item.reviewStatus]}</Badge></div><p className="mt-2 text-xs text-slate-500">{item.category} · {item.level} · {item.lessonCount} 节 · {item.duration} · {item.version}</p><p className="mt-2 text-xs text-slate-500">业务：{item.businessOwner} · 内容：{item.contentOwner} · 复审：{item.reviewDueAt ? toInputDate(item.reviewDueAt) : "未设"}</p><p className="mt-2 line-clamp-2 text-sm text-slate-500">{item.description}</p></div><Button onClick={() => setPath({ id: item.id, title: item.title, description: item.description, level: item.level, category: item.category, duration: item.duration, lessonCount: item.lessonCount, accent: item.accent, tags: (item.tags as string[]).join("，"), prerequisitePathIds: (item.prerequisitePathIds as number[]).join("，"), lifecycleStatus: item.lifecycleStatus, isFeatured: Boolean(item.isFeatured), contentOwner: item.contentOwner, businessOwner: item.businessOwner, reviewStatus: item.reviewStatus, reviewDueAt: toInputDate(item.reviewDueAt), version: item.version, changeNote: item.changeNote || "" })} size="sm" variant="ghost" className="text-violet-700">维护</Button></div></article>)}</div></div>
  <div className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><Header icon={FileStack} title="课程与资源台账" note="资源链接、责任人、版本与复审日期共同决定课程是否可长期发布。" /><div className="mt-5 space-y-3">{data.courses.map(item => <article key={item.id} className="rounded-2xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><h3 className="font-semibold">{item.title}</h3><Badge className={statusTone[item.lifecycleStatus]}>{item.lifecycleStatus}</Badge><Badge className={reviewTone[item.reviewStatus]}>{reviewText[item.reviewStatus]}</Badge></div><p className="mt-1 text-xs text-slate-500">路径：{data.paths.find(path => path.id === item.pathId)?.title || `#${item.pathId}`} · {item.resourceType} · 排序 {item.orderIndex} · {item.version}</p><p className="mt-2 text-xs text-slate-500">业务：{item.businessOwner} · 内容：{item.contentOwner} · 复审：{item.reviewDueAt ? toInputDate(item.reviewDueAt) : "未设"}</p><p className="mt-2 line-clamp-2 text-sm text-slate-500">{item.summary}</p><p className="mt-2 text-xs text-slate-400">{item.resourceUrl ? "已配置资源链接" : "尚未配置资源链接"}</p></div><Button onClick={() => setCourse({ id: item.id, pathId: item.pathId, title: item.title, summary: item.summary, duration: item.duration, orderIndex: item.orderIndex, resourceType: item.resourceType, resourceUrl: item.resourceUrl || "", tags: (item.tags as string[]).join("，"), prerequisiteCourseIds: (item.prerequisiteCourseIds as number[]).join("，"), lifecycleStatus: item.lifecycleStatus, contentOwner: item.contentOwner, businessOwner: item.businessOwner, reviewStatus: item.reviewStatus, reviewDueAt: toInputDate(item.reviewDueAt), version: item.version, changeNote: item.changeNote || "" })} size="sm" variant="ghost" className="text-violet-700">维护</Button></div></article>)}</div></div></section>
  <CourseMaterialManager courses={data.courses} materials={data.materials} refresh={refresh} /><PathDialog draft={path} setDraft={setPath} onSave={savePath} busy={addPath.isPending || updatePath.isPending} /><CourseDialog draft={course} setDraft={setCourse} paths={data.paths} onSave={saveCourse} busy={addCourse.isPending || updateCourse.isPending} />
  </main></PlatformShell>;
}
function Header({ icon: Icon, title, note }: { icon: typeof Route; title: string; note: string }) { return <div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50"><Icon className="h-5 w-5 text-violet-700" /></span><div><h2 className="font-serif text-xl font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{note}</p></div></div>; }
function Stat({ icon: Icon, value, label, note }: { icon: typeof Route; value: string; label: string; note: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50"><Icon className="h-5 w-5 text-violet-700" /></span><p className="mt-4 text-3xl font-semibold">{value}</p><p className="mt-1 font-medium">{label}</p><p className="mt-1 text-xs text-slate-400">{note}</p></article>; }
function GuideStep({ number, title, text }: { number: string; title: string; text: string }) { return <article className="rounded-2xl bg-white p-4 shadow-sm"><span className="text-xs font-bold tracking-[0.18em] text-violet-600">{number}</span><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></article>; }
function LedgerFieldsForm<T extends LedgerFields>({ draft, setDraft }: { draft: T; setDraft: (value: T) => void }) { return <><div className="grid grid-cols-2 gap-3"><Input value={draft.businessOwner} onChange={e => setDraft({ ...draft, businessOwner: e.target.value })} placeholder="业务负责人" /><Input value={draft.contentOwner} onChange={e => setDraft({ ...draft, contentOwner: e.target.value })} placeholder="内容负责人" /></div><div className="grid grid-cols-3 gap-3"><Input value={draft.version} onChange={e => setDraft({ ...draft, version: e.target.value })} placeholder="版本，如 v1.1" /><Input type="date" value={draft.reviewDueAt} onChange={e => setDraft({ ...draft, reviewDueAt: e.target.value })} /><select value={draft.reviewStatus} onChange={e => setDraft({ ...draft, reviewStatus: e.target.value as Review })} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="current">复审正常</option><option value="due">待复审</option><option value="overdue">复审逾期</option></select></div><Textarea value={draft.changeNote} onChange={e => setDraft({ ...draft, changeNote: e.target.value })} placeholder="本次更新说明（如资源替换、内容修订、适用范围调整）" /></>; }
function PathDialog({ draft, setDraft, onSave, busy }: { draft: PathDraft | null; setDraft: (value: PathDraft | null) => void; onSave: () => void; busy: boolean }) { return <Dialog open={Boolean(draft)} onOpenChange={open => !open && setDraft(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{draft?.id ? "维护学习路径台账" : "新建学习路径"}</DialogTitle></DialogHeader>{draft && <div className="grid gap-3 py-2"><Input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="路径标题" /><Textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} placeholder="能力目标与适用人群" /><div className="grid grid-cols-2 gap-3"><select value={draft.level} onChange={e => setDraft({ ...draft, level: e.target.value as PathDraft["level"] })} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="beginner">入门</option><option value="intermediate">进阶</option><option value="advanced">高级</option></select><Input value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })} placeholder="分类" /></div><div className="grid grid-cols-3 gap-3"><Input value={draft.duration} onChange={e => setDraft({ ...draft, duration: e.target.value })} placeholder="时长" /><Input type="number" value={draft.lessonCount} onChange={e => setDraft({ ...draft, lessonCount: Number(e.target.value) })} placeholder="课程数" /><Input value={draft.accent} onChange={e => setDraft({ ...draft, accent: e.target.value })} placeholder="主题色" /></div><Input value={draft.tags} onChange={e => setDraft({ ...draft, tags: e.target.value })} placeholder="标签，逗号分隔" /><Input value={draft.prerequisitePathIds} onChange={e => setDraft({ ...draft, prerequisitePathIds: e.target.value })} placeholder="先修路径 ID，逗号分隔" /><LedgerFieldsForm draft={draft} setDraft={setDraft} /><select value={draft.lifecycleStatus} onChange={e => setDraft({ ...draft, lifecycleStatus: e.target.value as Lifecycle })} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="draft">草稿</option><option value="published">发布</option><option value="archived">归档</option></select><label className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm">设为推荐路径<Switch checked={draft.isFeatured} onCheckedChange={checked => setDraft({ ...draft, isFeatured: checked })} /></label></div>}<DialogFooter><Button variant="outline" onClick={() => setDraft(null)}>取消</Button><Button disabled={!draft?.title || !draft.description || !draft.category || busy} onClick={onSave}>保存台账</Button></DialogFooter></DialogContent></Dialog>; }
function CourseDialog({ draft, setDraft, paths, onSave, busy }: { draft: CourseDraft | null; setDraft: (value: CourseDraft | null) => void; paths: Array<{ id: number; title: string }>; onSave: () => void; busy: boolean }) { return <Dialog open={Boolean(draft)} onOpenChange={open => !open && setDraft(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{draft?.id ? "维护课程台账" : "新建课程"}</DialogTitle></DialogHeader>{draft && <div className="grid gap-3 py-2"><select value={draft.pathId} onChange={e => setDraft({ ...draft, pathId: Number(e.target.value) })} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value={0}>选择所属路径</option>{paths.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><Input value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="课程标题" /><Textarea value={draft.summary} onChange={e => setDraft({ ...draft, summary: e.target.value })} placeholder="课程摘要" /><div className="grid grid-cols-3 gap-3"><Input value={draft.duration} onChange={e => setDraft({ ...draft, duration: e.target.value })} placeholder="时长" /><Input type="number" value={draft.orderIndex} onChange={e => setDraft({ ...draft, orderIndex: Number(e.target.value) })} placeholder="排序" /><select value={draft.resourceType} onChange={e => setDraft({ ...draft, resourceType: e.target.value as CourseDraft["resourceType"] })} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="article">文章</option><option value="video">视频</option><option value="exercise">练习</option><option value="template">模板</option></select></div><Input value={draft.resourceUrl} onChange={e => setDraft({ ...draft, resourceUrl: e.target.value })} placeholder="资源链接（可选）" /><Input value={draft.tags} onChange={e => setDraft({ ...draft, tags: e.target.value })} placeholder="标签，逗号分隔" /><Input value={draft.prerequisiteCourseIds} onChange={e => setDraft({ ...draft, prerequisiteCourseIds: e.target.value })} placeholder="先修课程 ID，逗号分隔" /><LedgerFieldsForm draft={draft} setDraft={setDraft} /><select value={draft.lifecycleStatus} onChange={e => setDraft({ ...draft, lifecycleStatus: e.target.value as Lifecycle })} className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="draft">草稿</option><option value="published">发布</option><option value="archived">归档</option></select></div>}<DialogFooter><Button variant="outline" onClick={() => setDraft(null)}>取消</Button><Button disabled={!draft?.pathId || !draft.title || !draft.summary || !draft.duration || busy} onClick={onSave}>保存台账</Button></DialogFooter></DialogContent></Dialog>; }
