import PlatformShell from "@/components/PlatformShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { resolveDocumentDisplay, VIDEO_PLAYBACK_SPEEDS } from "@/lib/courseExperience";
import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, FileText, Loader2, MessageCircle, PlayCircle, Send, Sparkles, Video } from "lucide-react";
import { Streamdown } from "streamdown";
import { useMemo, useRef, useState } from "react";
import { useLocation, useRoute } from "wouter";

type Material = { id: number; materialType: "document" | "video" | "practice"; sourceType: "url" | "file" | "inline"; title: string; description: string | null; sourceUrl: string | null; signedUrl: string | null; mimeType: string | null; content: string | null; config: Record<string, unknown>; orderIndex: number };
export default function CourseDetail() {
  const [, params] = useRoute("/learn/:pathId/course/:courseId"); const [, setLocation] = useLocation(); const pathId = Number(params?.pathId); const courseId = Number(params?.courseId); const { data: catalog, isLoading } = trpc.platform.catalog.useQuery(); const { data: personal } = trpc.platform.personal.get.useQuery(); const { data: experience } = trpc.platform.learning.courseExperience.useQuery({ courseId }, { enabled: Number.isInteger(courseId) && courseId > 0 }); const utils = trpc.useUtils(); const update = trpc.platform.personal.updateProgress.useMutation({ onSuccess: () => utils.platform.personal.get.invalidate() });
  const progress = useMemo(() => new Map((personal?.progress ?? []).map(item => [item.courseId, item.progress])), [personal?.progress]);
  if (isLoading || !catalog) return <PlatformShell><div className="grid min-h-[70vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-violet-600" /></div></PlatformShell>;
  const path = catalog.paths.find(item => item.id === pathId); const course = catalog.courses.find(item => item.id === courseId && item.pathId === pathId);
  if (!path || !course) return <PlatformShell><main className="mx-auto max-w-3xl px-4 py-20"><h1 className="font-serif text-3xl">该课程暂不可用</h1><Button onClick={() => setLocation(`/learn/${pathId}`)} className="mt-6">返回学习路径</Button></main></PlatformShell>;
  const done = progress.get(course.id) === 100; const Icon = course.resourceType === "video" ? Video : course.resourceType === "article" ? FileText : PlayCircle; const materials = experience?.materials as Material[] | undefined;
  return <PlatformShell><main className="mx-auto max-w-4xl px-4 py-8"><button onClick={() => setLocation(`/learn/${pathId}`)} className="flex items-center text-sm text-slate-500 hover:text-violet-700"><ArrowLeft className="mr-2 h-4 w-4" />返回「{path.title}」</button><article className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="bg-gradient-to-br from-slate-950 to-indigo-950 p-7 text-white md:p-10"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold tracking-[.16em] text-violet-300">COURSE / {path.category}</p><h1 className="mt-3 font-serif text-4xl">{course.title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300">{course.summary}</p></div><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-white/10"><Icon className="h-6 w-6 text-violet-200" /></span></div><div className="mt-7 flex flex-wrap gap-2"><Badge className="bg-white/10 text-violet-100 hover:bg-white/10">{course.resourceType}</Badge><span className="flex items-center rounded-full bg-white/10 px-3 py-1 text-xs text-slate-200"><Clock3 className="mr-1.5 h-3.5 w-3.5" />{course.duration}</span>{(course.tags as string[]).map(tag => <Badge key={tag} className="bg-white/10 text-violet-100 hover:bg-white/10">{tag}</Badge>)}</div></div><div className="p-6 md:p-8"><h2 className="text-lg font-semibold">本节学习资源</h2><p className="mt-2 text-sm text-slate-500">资源可由内容负责人持续替换；视频评论与模型实操结果只对你的学习过程可见。</p><div className="mt-5 space-y-5">{materials?.length ? materials.map(material => <MaterialPanel key={material.id} material={material} comments={experience?.comments ?? []} runs={experience?.runs ?? []} />) : course.resourceUrl ? <a href={course.resourceUrl} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-violet-200 bg-violet-50 px-5 py-4 text-sm font-semibold text-violet-800 transition hover:bg-violet-100"><span>打开课程资源</span><ExternalLink className="h-4 w-4" /></a> : <div className="rounded-xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-800">课程资源正在复审或维护中，完成阅读说明后可先标记学习进度。</div>}</div><div className="mt-8 flex flex-col gap-4 rounded-xl border border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">完成状态</p><p className="mt-1 text-sm text-slate-500">{done ? "你已完成本节任务，可继续浏览路径其他内容。" : "完成阅读、观看或实操后，标记为已完成。"}</p></div><Button disabled={done || update.isPending} onClick={() => update.mutate({ courseId: course.id, progress: 100 })} className="rounded-lg">{done ? <><CheckCircle2 className="mr-2 h-4 w-4" />已完成</> : "标记为完成"}</Button></div><Progress value={done ? 100 : 0} className="mt-4 h-1.5" /></div></article></main></PlatformShell>;
}
function MaterialPanel({ material, comments, runs }: { material: Material; comments: Array<{ comment: { id: number; materialId: number; content: string; videoSecond: number | null; createdAt: Date }; authorName: string | null }>; runs: Array<{ id: number; materialId: number; prompt: string; output: string; modelId: string; createdAt: Date }> }) { return <section className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Badge variant="secondary">{material.materialType === "document" ? "文档" : material.materialType === "video" ? "视频" : "实操"}</Badge><h3 className="font-semibold">{material.title}</h3></div>{material.description && <p className="mt-2 text-sm text-slate-500">{material.description}</p>}</div>{material.sourceUrl && <a href={material.sourceUrl} target="_blank" rel="noreferrer" className="text-sm font-medium text-violet-700">原始来源</a>}</div>{material.materialType === "document" && <DocumentMaterial material={material} />}{material.materialType === "video" && <VideoMaterial material={material} comments={comments.filter(item => item.comment.materialId === material.id)} />}{material.materialType === "practice" && <PracticeMaterial material={material} runs={runs.filter(item => item.materialId === material.id)} />}</section>; }
function DocumentMaterial({ material }: { material: Material }) { const url = material.signedUrl || material.sourceUrl; const display = resolveDocumentDisplay({ content: material.content, mimeType: material.mimeType, url }); return <div className="mt-4">{display === "markdown" ? <div className="prose prose-slate max-w-none rounded-xl bg-slate-50 p-5"><Streamdown>{material.content || ""}</Streamdown></div> : display === "image" ? <img className="max-h-[620px] w-full rounded-xl border border-slate-200 object-contain" src={url || ""} alt={material.title} /> : display === "pdf" ? <iframe className="h-[520px] w-full rounded-xl border" src={url || ""} title={material.title} /> : display === "link" ? <a href={url || "#"} target="_blank" rel="noreferrer" className="mt-2 flex items-center justify-between rounded-xl bg-violet-50 px-4 py-3 text-sm font-medium text-violet-800">打开或下载文档 <ExternalLink className="h-4 w-4" /></a> : <p className="text-sm text-amber-700">文档内容正在维护。</p>}</div>; }
function VideoMaterial({ material, comments }: { material: Material; comments: Array<{ comment: { id: number; content: string; videoSecond: number | null; createdAt: Date }; authorName: string | null }> }) { const video = useRef<HTMLVideoElement>(null); const [speed, setSpeed] = useState("1"); const [second, setSecond] = useState<number | null>(null); const [comment, setComment] = useState(""); const utils = trpc.useUtils(); const add = trpc.platform.learning.addComment.useMutation({ onSuccess: () => { setComment(""); utils.platform.learning.courseExperience.invalidate(); } }); const url = material.signedUrl || material.sourceUrl; return <div className="mt-4"><div className="relative overflow-hidden rounded-xl bg-slate-950">{url ? <video ref={video} controls className="aspect-video w-full" src={url} onTimeUpdate={() => setSecond(Math.floor(video.current?.currentTime ?? 0))} /> : <div className="grid aspect-video place-items-center text-sm text-slate-300">视频文件正在维护</div>}<div className="absolute right-3 top-3 rounded-lg bg-black/60 px-2 py-1 text-xs text-white">{comments.filter(item => item.comment.videoSecond !== null && Math.abs((item.comment.videoSecond ?? 0) - (second ?? 0)) < 4).slice(0, 2).map(item => <p key={item.comment.id}>「{item.comment.content}」</p>)}</div></div><div className="mt-3 flex items-center gap-3 text-sm"><label>倍速 <select value={speed} onChange={event => { setSpeed(event.target.value); if (video.current) video.current.playbackRate = Number(event.target.value); }} className="ml-1 rounded border px-2 py-1">{VIDEO_PLAYBACK_SPEEDS.map(option => <option key={option} value={option}>{option}×</option>)}</select></label><span className="text-slate-400">当前时间 {second ?? 0}s</span></div><div className="mt-4 flex gap-2"><Textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="写下时间戳评论，可作为轻量弹幕显示" className="min-h-10" /><Button disabled={!comment.trim() || add.isPending} onClick={() => add.mutate({ materialId: material.id, content: comment.trim(), videoSecond: second })}><Send className="h-4 w-4" /></Button></div><div className="mt-4 space-y-2">{comments.slice(-5).reverse().map(item => <div key={item.comment.id} className="flex gap-2 text-sm"><MessageCircle className="mt-0.5 h-4 w-4 text-violet-600" /><p><span className="font-medium">{item.authorName || "员工"}</span>{item.comment.videoSecond !== null && <span className="mx-1 text-violet-700">@ {item.comment.videoSecond}s</span>}{item.comment.content}</p></div>)}</div></div>; }
function PracticeMaterial({ material, runs }: { material: Material; runs: Array<{ id: number; prompt: string; output: string; modelId: string; createdAt: Date }> }) { const [prompt, setPrompt] = useState(""); const [output, setOutput] = useState(""); const run = trpc.platform.learning.runPractice.useMutation({ onSuccess: result => setOutput(result.output) }); return <div className="mt-4 rounded-xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-violet-300" /><p className="text-sm font-semibold">受控模型实操台</p></div><p className="mt-2 text-xs leading-5 text-slate-300">仅运行课程定义的 AI 任务，不执行代码、浏览器或外部系统操作；每天最多 5 次，结果仅归属当前学习者。</p><Textarea value={prompt} onChange={event => setPrompt(event.target.value)} className="mt-4 border-white/20 bg-white/10 text-white placeholder:text-slate-400" placeholder="输入你的业务素材或任务描述" /><Button disabled={prompt.trim().length < 2 || run.isPending} onClick={() => run.mutate({ materialId: material.id, prompt: prompt.trim() })} className="mt-3 bg-violet-500 hover:bg-violet-400">{run.isPending ? "正在运行" : "运行并获取结果"}</Button>{output && <div className="prose prose-invert mt-5 max-w-none rounded-xl bg-white/10 p-4"><Streamdown>{output}</Streamdown></div>}{runs.length > 0 && <div className="mt-5 border-t border-white/10 pt-4"><p className="text-xs font-semibold text-slate-300">我的最近运行</p>{runs.slice(0, 3).map(item => <p key={item.id} className="mt-2 line-clamp-2 text-xs text-slate-400">{item.modelId} · {item.prompt}</p>)}</div>}</div>; }
